contactinfoph:
    pattern:  /
    defaults: { _controller: "CrmAbonentBundle:ContactInfoPh:index" }

contactinfoph_show:
    pattern:  /{id}/show
    defaults: { _controller: "CrmAbonentBundle:ContactInfoPh:show" }

contactinfoph_new:
    pattern:  /new
    defaults: { _controller: "CrmAbonentBundle:ContactInfoPh:new" }

contactinfoph_create:
    pattern:  /create
    defaults: { _controller: "CrmAbonentBundle:ContactInfoPh:create" }
    requirements: { _method: post }

contactinfoph_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CrmAbonentBundle:ContactInfoPh:edit" }

contactinfoph_update:
    pattern:  /{id}/update
    defaults: { _controller: "CrmAbonentBundle:ContactInfoPh:update" }
    requirements: { _method: post|put }

contactinfoph_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CrmAbonentBundle:ContactInfoPh:delete" }
    requirements: { _method: post|delete }
