parameters:
#    crm_addresses.example.class: Crm\AddressesBundle\Example

services:
#    crm_addresses.example:
#        class: %crm_addresses.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
