# FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: fos_userbundle
    user_class: Zk\UserBundle\Entity\User
    profile:
        form:
            type:               zk_user_profile
            name:               fos_user_profile_form
            validation_groups:  [Profile, Default]
    resetting:
        token_ttl: 86400
        email:
            from_email: 
                address:  %mailer_user%
                sender_name: Rodina.TV
            template:   RodinaCabinetBundle:Security:resetting_email.html.twig
    service:
        mailer: fos_user.mailer.twig_swift