crm_abonent:
    resource: "@CrmAbonentBundle/Resources/config/routing.yml"
    prefix:   /

crm_addresses:
    resource: "@CrmAddressesBundle/Resources/config/routing.yml"
    prefix:   /

zk_interface:
    resource: "@ZkInterfaceBundle/Resources/config/routing.yml"
    prefix:   /

zk_user:
    resource: "@ZkUserBundle/Resources/config/routing.yml"
    prefix:   /

# FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
#FOSJsRoutingBundle
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

logout:
    pattern:  /logout

login:
    pattern:  /login
