jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        fos_userbundle:
            class: Zk\UserBundle\Entity\User
            algorithm: sha512
            encode-as-base64: true
            iterations: 4

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        #login:
        #    pattern:  ^/(cabinet|manager)/login$
        #    anonymous: true 
        #    security: false

        crm:
            provider: fos_userbundle
            pattern:    ^/.*
            form_login:
                login_path:     fos_user_security_login 
                check_path:     fos_user_security_check
                default_target_path: /house/list
                csrf_provider:  form.csrf_provider
            logout: 
                path:   /logout
                target: /login
                invalidate_session: false
            anonymous: true 
            security: true
            switch_user: { role: ROLE_ADMIN, parameter: __crm }
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/.*, role: ROLE_USER, requires_channel: https }
        
