<?php

namespace Crm\AbonentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AbonentFizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonentPhRepository extends EntityRepository
{
}
