<?php

namespace Crm\AbonentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbonentPrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonentPrRepository extends EntityRepository
{
}
