<?php

namespace Crm\AbonentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbonentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonentRepository extends EntityRepository
{
}
