<?php

namespace Zk\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserViewRepository extends EntityRepository
{
}
