parameters:
#    crm_abonent.example.class: Crm\AbonentBundle\Example

services:
    crm.change_update.listener:
        class:  Crm\AbonentBundle\Listener\ChangeUpdateListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
            - { name: doctrine.event_listener, event: postUpdate,  method: postUpdate }
            - { name: doctrine.event_listener, event: preUpdate,   method: preUpdate }
            - { name: doctrine.event_listener, event: prePersist,  method: prePersist }
