<?php

namespace Crm\AddressesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParadRepository extends EntityRepository
{
}
