<?php

namespace Crm\AddressesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StreetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreetRepository extends EntityRepository
{
}
