<?php

namespace Crm\AddressesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SwitchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SwitchDeviceRepository extends EntityRepository
{
}
